<?php

namespace App\Tests\Units\Entity;

use App\Entity\Customer;
use App\Entity\Order;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use PHPUnit\Framework\TestCase;

class CustomerTest extends TestCase
{
    private Customer $customer;

    private Order $order;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->customer = new Customer();
        $this->order = new Order();
    }

    /**
     * @group entity
     * @group customer
     * @group customer-default
     */
    public function testDefault(): void
    {
        $this->assertEmpty($this->customer->getShippingAddress());
        $this->assertIsString($this->customer->getShippingAddress());
        $this->assertNull($this->customer->getBirthDate());
        $this->assertEmpty($this->customer->getOrders());
        $this->assertInstanceOf(ArrayCollection::class, $this->customer->getOrders());
    }

    /**
     * @group entity
     * @group customer
     * @group customer-set-shipping-address
     */
    public function testSetShippingAddress(): void
    {
        $this->customer->setShippingAddress("123 Main St");
        $this->assertSame("123 Main St", $this->customer->getShippingAddress());
    }

    /**
     * @group entity
     * @group customer
     * @group customer-set-birth-date
     */
    public function testSetBirthDate(): void
    {
        $this->customer->setBirthDate(new DateTime());
        $this->assertInstanceOf(DateTimeInterface::class, $this->customer->getBirthDate());
    }

    /**
     * @group entity
     * @group customer
     * @group customer-set-orders
     */
    public function testSetOrders(): void
    {
        $orders = new ArrayCollection();
        for ($i = 0; $i < 5; $i++) {
            $orders->add(new Order());
        }
        $this->customer->setOrders($orders);
        $this->assertInstanceOf(ArrayCollection::class, $this->customer->getOrders());
        $this->assertContainsOnlyInstancesOf(Order::class, $this->customer->getOrders());
    }

    /**
     * @group entity
     * @group customer
     * @group customer-add-order
     */
    public function testAddOrder(): void
    {
        $this->customer->addOrder($this->order);
        $this->assertInstanceOf(ArrayCollection::class, $this->customer->getOrders());
        $this->assertContainsOnlyInstancesOf(Order::class, $this->customer->getOrders());
    }

    /**
     * @group entity
     * @group customer
     * @group customer-add-order-twice
     */
    public function testCannotAddSameOrderTwice(): void
    {
        $this->customer->addOrder($this->order);
        $this->customer->addOrder($this->order);
        $this->assertCount(1, $this->customer->getOrders());
    }

    /**
     * @group entity
     * @group customer
     * @group customer-remove-order
     */
    public function testRemoveOrder(): void
    {
        $this->customer->addOrder($this->order);
        $this->customer->removeOrder($this->order);
        $this->assertEmpty($this->customer->getOrders());
    }
}