<?php

namespace App\Tests\Entity;

use App\Entity\User;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

class UserTest extends TestCase
{

    /**
     * @var User
     */
    private User $user;

    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = $this->getMockForAbstractClass('App\Entity\User');
    }

    /**
     * @group entity
     * @group user
     * @group user-default
     */
    public function testDefault(): void
    {
        $this->assertNull($this->user->getId());
        $this->assertIsString($this->user->getFirstName());
        $this->assertEmpty($this->user->getFirstName());
        $this->assertIsString($this->user->getLastName());
        $this->assertEmpty($this->user->getLastName());
        $this->assertIsString($this->user->getEmail());
        $this->assertEmpty($this->user->getEmail());
        $this->assertIsString($this->user->getPassword());
        $this->assertEmpty($this->user->getPassword());
        $this->assertIsString($this->user->getCity());
        $this->assertEmpty($this->user->getCity());
        $this->assertIsString($this->user->getStreet());
        $this->assertEmpty($this->user->getStreet());
        $this->assertIsString($this->user->getStreetNumber());
        $this->assertEmpty($this->user->getStreetNumber());
        $this->assertIsString($this->user->getPostalCode());
        $this->assertEmpty($this->user->getPostalCode());
        $this->assertIsString($this->user->getPhone());
        $this->assertEmpty($this->user->getPhone());
        $this->assertIsArray($this->user->getRoles());
        $this->assertEmpty($this->user->getRoles());
        $this->assertIsBool($this->user->isVerified());
        $this->assertFalse($this->user->isVerified());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-firstname
     */
    public function testSetFirstName(): void
    {
        $this->user->setFirstName("John");

        $this->assertSame("John", $this->user->getFirstName());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-lastname
     */
    public function testSetLastName(): void
    {
        $this->user->setLastName("Doe");

        $this->assertSame("Doe", $this->user->getLastName());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-email
     */
    public function testSetEmail(): void
    {
        $this->user->setEmail("test@dev.com");

        $this->assertSame("test@dev.com", $this->user->getEmail());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-city
     */
    public function testSetCity(): void
    {
        $this->user->setCity("Paris");

        $this->assertSame("Paris", $this->user->getCity());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-street
     */
    public function testSetStreet(): void
    {
        $this->user->setStreet("Rue de la Paix");

        $this->assertSame("Rue de la Paix", $this->user->getStreet());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-street-number
     */
    public function testSetStreetNumber(): void
    {
        $this->user->setStreetNumber("1");

        $this->assertSame("1", $this->user->getStreetNumber());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-postal-code
     */
    public function testSetPostalCode(): void
    {
        $this->user->setPostalCode("75000");

        $this->assertSame("75000", $this->user->getPostalCode());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-phone
     */
    public function testSetPhone(): void
    {
        $this->user->setPhone("0606060606");

        $this->assertSame("+33606060606", $this->user->getPhone());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-roles
     */
    public function testSetRoles(): void
    {
        $this->user->setRoles(["ROLE_USER"]);

        $this->assertSame(["ROLE_USER"], $this->user->getRoles());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-password
     */
    public function testSetPassword(): void
    {
        $this->user->setPassword("password");

        $this->assertSame("password", $this->user->getPassword());
    }

    /**
     * @group entity
     * @group user
     * @group user-get-user-identifier
     */
    public function testGetUserIdentifier(): void
    {
        $this->user->setEmail("test@dev.com");

        $this->assertSame("test@dev.com", $this->user->getUserIdentifier());
    }

    /**
     * @group entity
     * @group user
     * @group user-get-salt
     */
    public function testGetSalt(): void
    {
        $this->assertNull($this->user->getSalt());
    }

    /**
     * @group entity
     * @group user
     * @group user-erase-credentials
     */
    public function testEraseCredentials(): void
    {
        $this->assertNull($this->user->eraseCredentials());
    }

    /**
     * @group entity
     * @group user
     * @group user-set-is-verified
     */
    public function testSetIsVerified(): void
    {
        $this->user->setIsVerified(true);

        $this->assertTrue($this->user->isVerified());
    }

}